from project_configuration.BeautyCFG import BeautyCFG
from project_configuration.DataCFG import DataCFG
from project_configuration.PreprocessingCFG import PreprocessingCFG
from project_configuration.TrainCFG import TrainCFG